version: '3'

services:

#  postgres:
#    container_name: postgres-song-db
#    image: postgres:11.3
#    restart: always
#    environment:
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: root
#      POSTGRES_DB: songs
#    ports:
#      - '54322:5432'
#    volumes:
#      - ./infra/psql_init_scripts:/docker-entrypoint-initdb.d/

  localstack:
    container_name: localstack
    image: localstack/localstack
    network_mode: bridge
    ports:
      - '127.0.0.1:4510-4559:4510-4559'  # external service port range
      - '127.0.0.1:4566:4566'            # LocalStack Edge Proxy
    environment:
      # - DEBUG=${DEBUG-}
      # - DATA_DIR=${DATA_DIR-}
      # - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      # - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      # - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3
    # volumes:
      # - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      # - "/var/run/docker.sock:/var/run/docker.sock"

  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - '8101:8101'
    environment:
      SERVER_PORT: 8101
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - zookeeper
      - kafka

  pact-broker:
    container_name: pact-broker
    image: pactfoundation/pact-broker:2.101.0.1
    ports:
      - '9292:9292'
    environment:
      PACT_BROKER_PORT: '9292'
      PACT_BROKER_DATABASE_URL: 'postgres://pact:pass@pact-broker.postgres/pact_broker'
      PACT_BROKER_LOG_LEVEL: DEBUG
      PACT_BROKER_SQL_LOG_LEVEL: DEBUG
    depends_on:
      - pact-broker-postgres

  pact-broker-postgres:
    container_name: pact-broker.postgres
    image: postgres:14.4
    environment:
      POSTGRES_DB: pact_broker
      POSTGRES_USER: pact
      POSTGRES_PASSWORD: pass
