spring:
  jpa:
    generate-ddl: true
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson.default-property-inclusion: non_null
  h2.console.enabled: true

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:54322}/${POSTGRES_DATABASE:song_service}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

server:
  port: 8082
  error:
    whitelabel.enabled: false
    include-stacktrace: ALWAYS
    include-message: ALWAYS
