pactbroker:
  host: localhost
  port: 9292
  tags: latest

spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      auto-offset-reset: earliest
      group-id: resource-service-test

test.kafka.consumer.timeout: 1000