spring:
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
cloud:
    aws:
        region:
            static: us-east-1
            auto: false
        credentials:
            access-key: localstack
            secret-key: localstack
        stack:
            auto: false
            enabled: false
        s3:
            endpoint: http://127.0.0.1:4566

resource:
    s3:
        bucket-name: songs