server.port: 8081

cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: localstack
      secret-key: localstack
    stack:
      auto: false
      enabled: false
    s3:
      endpoint: http://127.0.0.1:4566

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  h2.console.enabled: true
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

resource.s3.bucket-name: songs
kafka.resource.topic.name: resources
